// ============================================
// SPELLING CATEGORIEËN & WOORDEN
// ============================================

export const SPELLING_CATEGORIES = [
  {
    id: 1,
    name: 'Hakwoord',
    rule: 'Ik schrijf het woord zoals ik het hoor.',
    example: 'kat',
    icon: '✂️',
  },
  {
    id: 2,
    name: 'Zingwoord',
    rule: 'Ik schrijf ng.',
    example: 'zing',
    icon: '🎵',
  },
  {
    id: 3,
    name: 'Luchtwoord',
    rule: 'Korte klank + cht van lucht. Behalve bij hij ligt, hij legt en hij zegt.',
    example: 'lucht',
    icon: '💨',
  },
  {
    id: 4,
    name: 'Plankwoord',
    rule: 'Daar mag niets tussen.',
    example: 'plank',
    icon: '🪵',
  },
  {
    id: 5,
    name: 'Eer-oor-eur-eel-woord',
    rule: 'Schrijf ee (eer/eel) of oo (oor) of eu (eur).',
    example: 'beer, hoor, geur, geel',
    icon: '🔤',
    subcategories: [
      { id: '5a', name: 'Eer-woord', rule: 'Ik schrijf ee.', example: 'beer' },
      { id: '5b', name: 'Oor-woord', rule: 'Ik schrijf oo.', example: 'hoor' },
      { id: '5c', name: 'Eur-woord', rule: 'Ik schrijf eu.', example: 'geur' },
      { id: '5d', name: 'Eel-woord', rule: 'Ik schrijf ee.', example: 'geel' },
    ],
  },
  {
    id: 6,
    name: 'Aai-ooi-oei-woord',
    rule: 'Ik schrijf i.',
    example: 'haai, mooi, loei',
    icon: '🌈',
  },
  {
    id: 7,
    name: 'Eeuw-ieuw-woord',
    rule: 'Ik denk aan de u.',
    example: 'leeuw, nieuw',
    icon: '✨',
  },
  {
    id: 8,
    name: 'Langermaakwoord',
    rule: 'Ik hoor een /t/ aan het eind, dus langermaken. Ik hoor of ik d of t moet schrijven.',
    example: 'hart, vind',
    icon: '📏',
  },
  {
    id: 9,
    name: 'Verkleinwoord',
    rule: 'Maak het verkleinwoord. Let op de juiste uitgang: -je, -tje, -pje, -etje, -kje.',
    example: 'huisje, bloempje, mannetje',
    icon: '🐣',
  },
  {
    id: 11,
    name: 'Lange klank',
    rule: 'Je hoort een lange klank: aa, ee, oo, uu. In een gesloten lettergreep schrijf je twee klinkers.',
    example: 'maan, boom, vuur',
    icon: '🔊',
  },
  {
    id: 12,
    name: 'Samenstelling',
    rule: 'Twee woorden die samen één nieuw woord maken.',
    example: 'voetbal, regenjas',
    icon: '🧩',
  },
  {
    id: 13,
    name: 'Hoofdletters',
    rule: 'Namen, plaatsen en feestdagen schrijf je met een hoofdletter.',
    example: 'Jan, Amsterdam, Kerstmis',
    icon: '🔠',
  },
  {
    id: 10,
    name: 'Meervoud',
    rule: 'Maak het meervoud. Let op: -en, -s, of -eren. Soms verdubbelt de medeklinker.',
    example: "katten, auto's, kinderen",
    icon: '👥',
  },
];

export const SPELLING_WORDS = {
  // 1. Hakwoorden (korte klank)
  1: [
    'kat',
    'mop',
    'bus',
    'pen',
    'dak',
    'vis',
    'pot',
    'map',
    'bel',
    'dop',
    'ham',
    'vel',
    'pit',
    'rok',
    'tas',
    'net',
    'kip',
    'bal',
    'mus',
    'lap',
    'sap',
    'pan',
    'man',
    'bak',
    'tak',
    'zak',
    'hek',
    'lek',
    'pet',
    'bed',
    'bok',
    'mok',
    'sok',
    'kop',
    'top',
    'lip',
    'rat',
    'mat',
    'lat',
    'gat',
    'pad',
    'bad',
    'rad',
    'kam',
    'ram',
    'dam',
    'som',
    'kom',
    'bom',
    'kus',
    'zus',
    'hut',
    'put',
    'rug',
  ],

  // 2. Zingwoorden (-ng)
  2: [
    'zing',
    'ring',
    'bang',
    'lang',
    'gang',
    'slang',
    'wang',
    'tang',
    'jong',
    'sprong',
    'ding',
    'ling',
    'long',
    'tong',
    'gong',
    'zang',
    'wring',
    'spring',
    'zong',
    'dwang',
    'drang',
    'stang',
    'vang',
    'hang',
    'kring',
  ],

  // 3. Luchtwoorden (-cht)
  3: [
    'lucht',
    'nacht',
    'recht',
    'slecht',
    'vocht',
    'macht',
    'pracht',
    'klacht',
    'dicht',
    'licht',
    'gracht',
    'plicht',
    'tocht',
    'wacht',
    'kracht',
    'bocht',
    'jacht',
    'zacht',
    'echt',
    'vlecht',
    'hecht',
    'knecht',
    'vlucht',
    'zucht',
  ],

  // 4. Plankwoorden (-nk)
  4: [
    'plank',
    'dank',
    'bank',
    'blank',
    'klink',
    'denk',
    'drink',
    'stink',
    'rank',
    'klank',
    'stank',
    'wenk',
    'blink',
    'tank',
    'honk',
    'vonk',
    'zink',
    'flink',
    'slank',
    'pronk',
  ],

  // 5a. Eer-woorden (je hoort i-klank)
  '5a': [
    'beer',
    'veer',
    'peer',
    'meer',
    'weer',
    'leer',
    'keer',
    'smeer',
    'sfeer',
    'neer',
    'zeer',
    'heer',
    'teer',
  ],

  // 5b. Oor-woorden (je hoort oo-klank)
  '5b': ['hoor', 'door', 'voor', 'boor', 'spoor', 'koor', 'stoor', 'vroor'],

  // 5c. Eur-woorden (je hoort eu-klank)
  '5c': [
    'geur',
    'deur',
    'kleur',
    'leur',
    'speur',
    'scheur',
    'sleur',
    'beurt',
    'zeur',
    'keur',
    'treur',
  ],

  // 5d. Eel-woorden (je hoort i-klank)
  '5d': [
    'geel',
    'veel',
    'deel',
    'heel',
    'steel',
    'speel',
    'streel',
    'scheel',
    'keel',
    'meel',
  ],

  // 6. Aai-ooi-oei
  6: [
    'mooi',
    'fraai',
    'draai',
    'haai',
    'maai',
    'kraai',
    'groei',
    'bloei',
    'boei',
    'hooi',
    'fooi',
    'gooi',
    'roei',
    'loei',
    'kooi',
    'zaai',
    'taai',
    'saai',
    'dooi',
    'tooi',
    'sproei',
    'knoei',
  ],

  // 7. Eeuw-ieuw
  7: [
    'nieuw',
    'leeuw',
    'meeuw',
    'sneeuw',
    'schreeuw',
    'spreeuw',
    'geeuw',
    'kieuw',
  ],

  // 8. Langermaakwoorden
  8: [
    'hart',
    'kaart',
    'paard',
    'hond',
    'mond',
    'hand',
    'land',
    'zand',
    'wand',
    'band',
    'rond',
    'bond',
    'bord',
    'woord',
    'aard',
    'baard',
    'waard',
    'koord',
    'staart',
    'taart',
    'zwaard',
    'vind',
    'brand',
    'krant',
    'plant',
    'stand',
    'kant',
    'tent',
    'punt',
    'sport',
    'kort',
    'start',
    'markt',
  ],

  // 9. Verkleinwoorden — objecten met { word, answer, suffix }
  9: [
    { word: 'huis', answer: 'huisje', suffix: '-je' },
    { word: 'boek', answer: 'boekje', suffix: '-je' },
    { word: 'vis', answer: 'visje', suffix: '-je' },
    { word: 'doos', answer: 'doosje', suffix: '-je' },
    { word: 'roos', answer: 'roosje', suffix: '-je' },
    { word: 'kaas', answer: 'kaasje', suffix: '-je' },
    { word: 'muis', answer: 'muisje', suffix: '-je' },
    { word: 'bloem', answer: 'bloempje', suffix: '-pje' },
    { word: 'boom', answer: 'boompje', suffix: '-pje' },
    { word: 'arm', answer: 'armpje', suffix: '-pje' },
    { word: 'worm', answer: 'wormpje', suffix: '-pje' },
    { word: 'duim', answer: 'duimpje', suffix: '-pje' },
    { word: 'kam', answer: 'kammetje', suffix: '-etje' },
    { word: 'bel', answer: 'belletje', suffix: '-etje' },
    { word: 'ster', answer: 'sterretje', suffix: '-etje' },
    { word: 'bal', answer: 'balletje', suffix: '-etje' },
    { word: 'zon', answer: 'zonnetje', suffix: '-etje' },
    { word: 'man', answer: 'mannetje', suffix: '-etje' },
    { word: 'pan', answer: 'pannetje', suffix: '-etje' },
    { word: 'bon', answer: 'bonnetje', suffix: '-etje' },
    { word: 'ring', answer: 'ringetje', suffix: '-etje' },
    { word: 'koning', answer: 'koninkje', suffix: '-kje' },
    { word: 'woning', answer: 'woninkje', suffix: '-kje' },
    { word: 'leerling', answer: 'leerlinkje', suffix: '-kje' },
    { word: 'punt', answer: 'puntje', suffix: '-je' },
    { word: 'boot', answer: 'bootje', suffix: '-je' },
    { word: 'trein', answer: 'treintje', suffix: '-tje' },
    { word: 'stoel', answer: 'stoeltje', suffix: '-tje' },
    { word: 'vogel', answer: 'vogeltje', suffix: '-tje' },
    { word: 'tafel', answer: 'tafeltje', suffix: '-tje' },
    { word: 'lepel', answer: 'lepeltje', suffix: '-tje' },
    { word: 'sleutel', answer: 'sleuteltje', suffix: '-tje' },
    { word: 'auto', answer: 'autootje', suffix: '-tje' },
    { word: 'paraplu', answer: 'parapluutje', suffix: '-tje' },
    { word: 'foto', answer: 'fotootje', suffix: '-tje' },
  ],

  // 10. Meervoud — objecten met { word, answer, suffix }
  10: [
    { word: 'kat', answer: 'katten', suffix: '-en' },
    { word: 'hond', answer: 'honden', suffix: '-en' },
    { word: 'boom', answer: 'bomen', suffix: '-en' },
    { word: 'stoel', answer: 'stoelen', suffix: '-en' },
    { word: 'muis', answer: 'muizen', suffix: '-en' },
    { word: 'huis', answer: 'huizen', suffix: '-en' },
    { word: 'vis', answer: 'vissen', suffix: '-en' },
    { word: 'pan', answer: 'pannen', suffix: '-en' },
    { word: 'bal', answer: 'ballen', suffix: '-en' },
    { word: 'man', answer: 'mannen', suffix: '-en' },
    { word: 'pen', answer: 'pennen', suffix: '-en' },
    { word: 'bed', answer: 'bedden', suffix: '-en' },
    { word: 'dak', answer: 'daken', suffix: '-en' },
    { word: 'fiets', answer: 'fietsen', suffix: '-en' },
    { word: 'broek', answer: 'broeken', suffix: '-en' },
    { word: 'auto', answer: "auto's", suffix: '-s' },
    { word: 'foto', answer: "foto's", suffix: '-s' },
    { word: 'paraplu', answer: "paraplu's", suffix: '-s' },
    { word: 'taxi', answer: "taxi's", suffix: '-s' },
    { word: 'baby', answer: "baby's", suffix: '-s' },
    { word: 'jongen', answer: 'jongens', suffix: '-s' },
    { word: 'meisje', answer: 'meisjes', suffix: '-s' },
    { word: 'tafel', answer: 'tafels', suffix: '-s' },
    { word: 'lepel', answer: 'lepels', suffix: '-s' },
    { word: 'sleutel', answer: 'sleutels', suffix: '-s' },
    { word: 'kind', answer: 'kinderen', suffix: '-eren' },
    { word: 'ei', answer: 'eieren', suffix: '-eren' },
    { word: 'lied', answer: 'liederen', suffix: '-eren' },
    { word: 'blad', answer: 'bladeren', suffix: '-eren' },
    { word: 'been', answer: 'beenderen', suffix: '-eren' },
    { word: 'rund', answer: 'runderen', suffix: '-eren' },
    { word: 'lam', answer: 'lammeren', suffix: '-eren' },
    { word: 'kalf', answer: 'kalveren', suffix: '-eren' },
    { word: 'volk', answer: 'volkeren', suffix: '-eren' },
    { word: 'glas', answer: 'glazen', suffix: '-en' },
  ],

  // 11. Lange klank (aa, ee, oo, uu — dubbele klinker in gesloten lettergreep)
  11: [
    'maan',
    'raam',
    'naam',
    'kaas',
    'baan',
    'laan',
    'paar',
    'schaap',
    'straat',
    'draad',
    'praat',
    'taal',
    'haan',
    'gaan',
    'kraal',
    'maat',
    'been',
    'teen',
    'steen',
    'keen',
    'zeep',
    'beek',
    'reep',
    'leeg',
    'streep',
    'week',
    'beet',
    'roos',
    'doos',
    'brood',
    'groot',
    'rood',
    'boot',
    'boon',
    'droog',
    'rook',
    'kool',
    'poot',
    'moot',
    'muur',
    'vuur',
    'buur',
    'duur',
    'puur',
    'stuur',
    'vaar',
    'loop',
    'boom',
    'lees',
    'noot',
    'weeg',
  ],

  // 12. Samenstellingen (twee woorden vormen samen één woord)
  12: [
    'voetbal',
    'huisdeur',
    'zonlicht',
    'schoolplein',
    'regenjas',
    'boekentas',
    'slaapkamer',
    'tandarts',
    'speelhoek',
    'fietsenstalling',
    'zonnebril',
    'waterfles',
    'handschoen',
    'boomhut',
    'zwembad',
    'rugzak',
    'schooltas',
    'regenboog',
    'sneeuwpop',
    'broodtrommel',
    'zandkasteel',
    'speeltuin',
    'huiswerk',
    'dierentuin',
    'boterham',
    'nachtlamp',
    'pannenkoek',
    'vliegtuig',
    'bloempot',
    'tuinslang',
    'voordeur',
    'badkamer',
    'kerstboom',
    'vogelhuis',
    'melkpak',
    'stoepkrijt',
  ],

  // 13. Hoofdletters (namen, plaatsen, feestdagen)
  13: [
    'Michael',
    'Emma',
    'Sophie',
    'Lucas',
    'Daan',
    'Lotte',
    'Bram',
    'Sara',
    'Anna',
    'Mo',
    'Khalid',
    'Noor',
    'Mila',
    'Liam',
    'Nederland',
    'Amsterdam',
    'Rotterdam',
    'Den Haag',
    'Utrecht',
    'Groningen',
    'Maastricht',
    'Eindhoven',
    'Nijmegen',
    'Europa',
    'Afrika',
    'Sinterklaas',
    'Kerstmis',
    'Pasen',
    'Koningsdag',
    'Pinksteren',
  ],
};
