// Thema's die kids van groep 4 leuk vinden
export const THEMES = {
  SPACE: {
    id: 'space',
    name: '🚀 Ruimte',
    emoji: '🚀',
    colors: {
      primary: 'bg-indigo-900',
      secondary: 'bg-purple-800',
      wall: 'bg-gray-800',
      path: 'bg-indigo-950',
      player: '👨‍🚀',
      challenge: '👽',
    },
    pathChar: '✦',
    friendlies: ['🛸', '🌟', '🌍', '🚀', '☄️', '🌌', '👾', '🛰️', '🪐', '🌠'],
    story: {
      intro: 'NOODOPROEP uit de ruimte! Een meteorietenregen heeft het ruimteschip geraakt en je vriendjes zijn door het heelal verspreid! Ze zweven verloren tussen de sterren en wachten tot iemand ze vindt. Kun jij door het ruimtestation navigeren en al je vriendjes veilig terugbrengen?',
      friendTexts: [
        'Hoera, je hebt me gevonden! Ik dreef al uren rond tussen de sterren!',
        'Eindelijk! Ik was zo bang dat niemand me zou vinden in deze donkere ruimte!',
        'Jippie! Nu kan ik weer terug naar het ruimteschip!',
        'Dankjewel! Ik zag alleen maar sterren en planeten, maar geen vriendjes!',
        'Yes! Ik wist dat je me zou komen redden, beste astronaut!',
        'Gelukkig! Ik was bijna in een zwart gat gevallen!',
        'Hoera! Samen vliegen we terug naar de aarde!',
        'Super! Ik miste jullie allemaal zo erg hier in de ruimte!',
        'Fantastisch! Laten we de anderen ook snel gaan zoeken!',
        'Wauw, je hebt me gevonden tussen al die meteorieten!',
      ],
      endingComplete: 'MISSIE GESLAAGD! 🚀 Alle ruimtevriendjes zijn weer veilig aan boord van het ruimteschip! Dankzij jouw moed en slimheid kan de crew nu veilig terug naar de aarde vliegen. Jij bent een echte ruimteheld!',
      endingIncomplete: 'Je verlaat het ruimtestation... maar niet al je vriendjes zijn gered. Ze zweven nog steeds verloren in de ruimte en hopen dat iemand ze vindt. 🥺',
      warningLeave: 'Wacht! Er zweven nog vriendjes verloren in de ruimte! Ze rekenen op jou om ze te vinden. Weet je zeker dat je ze achterlaat?',
    },
  },
  JUNGLE: {
    id: 'jungle',
    name: '🦁 Jungle',
    emoji: '🦁',
    colors: {
      primary: 'bg-green-700',
      secondary: 'bg-green-600',
      wall: 'bg-green-900',
      path: 'bg-green-800',
      player: '🧒',
      challenge: '🐒',
    },
    pathChar: '✿',
    friendlies: ['🦜', '🐘', '🦋', '🐸', '🐰', '🦁', '🦅', '🦧', '🦓', '🦥'],
    story: {
      intro: 'Help! Een grote storm heeft door de jungle geraasd en je diervriendjes zijn verdwaald in het dichte oerwoud! Ze zitten verstopt tussen de bomen en struiken en durven niet alleen verder. Trek de jungle in en breng al je vriendjes veilig terug naar de open plek!',
      friendTexts: [
        'Oef, gelukkig! Ik zat helemaal vast tussen de takken!',
        'Joehoe! Ik hoorde de apen, maar kon de weg niet meer vinden!',
        'Dankjewel! Het was zo donker hier tussen de grote bomen!',
        'Eindelijk een vriendelijk gezicht! De jungle is zo groot!',
        'Hoera! Ik was bang voor de geluiden in het oerwoud!',
        'Yes! Nu kan ik weer spelen bij de waterval!',
        'Fijn! Ik miste het zonlicht en mijn vriendjes!',
        'Super! Samen zijn we sterker in de jungle!',
        'Geweldig! Laten we de anderen ook gaan zoeken!',
        'Wauw, je hebt me gevonden tussen al die planten!',
      ],
      endingComplete: 'JUNGLE AVONTUUR VOLTOOID! 🦁 Alle diervriendjes zijn weer veilig samen op de open plek! De zon schijnt, de vogels fluiten en iedereen is weer herenigd. Jij bent een echte jungle-ontdekker!',
      endingIncomplete: 'Je verlaat de jungle... maar sommige vriendjes zijn nog steeds verdwaald tussen de bomen. Ze wachten nog steeds tot iemand ze vindt. 🥺',
      warningLeave: 'Wacht! Er zitten nog vriendjes verstopt in de jungle! Ze zijn bang en alleen. Weet je zeker dat je ze achterlaat?',
    },
  },
  OCEAN: {
    id: 'ocean',
    name: '🌊 Oceaan',
    emoji: '🌊',
    colors: {
      primary: 'bg-blue-600',
      secondary: 'bg-cyan-500',
      wall: 'bg-blue-900',
      path: 'bg-blue-700',
      player: '🤿',
      challenge: '🐠',
    },
    pathChar: '~',
    friendlies: ['🐙', '🦀', '🐬', '🦭', '🐚', '🦈', '🐳', '🦑', '🐡', '🪸'],
    story: {
      intro: 'SOS vanuit de diepzee! Een sterke stroming heeft je onderwatervriendjes meegevoerd naar alle hoeken van de oceaan! Ze zitten verstopt tussen het koraal en de zeeplanten. Duik de zee in en breng al je vriendjes weer veilig naar de onderwatergrot!',
      friendTexts: [
        'Blub blub! Eindelijk! Ik zwom al rondjes tussen het koraal!',
        'Joepie! De stroming was zo sterk, ik kon niet meer terug!',
        'Dankjewel! Ik verstopte me voor een grote vis!',
        'Hoera! Het is zo donker hier op de zeebodem!',
        'Yes! Nu kan ik weer zwemmen met mijn vriendjes!',
        'Gelukkig! Ik miste de warme wateren bij de grot!',
        'Super! Samen maken we de mooiste bubbels!',
        'Fijn! Ik was een beetje bang voor de haaien!',
        'Geweldig! Laten we de anderen ook gaan redden!',
        'Wauw, je hebt me gevonden in deze diepe zee!',
      ],
      endingComplete: 'DUIKMISSIE GESLAAGD! 🌊 Alle zeevriendjes zijn weer veilig samen in de onderwatergrot! De vissen zwemmen vrolijk rond en het koraal gloeit prachtig. Jij bent een echte oceaanheld!',
      endingIncomplete: 'Je zwemt naar de oppervlakte... maar niet alle vriendjes zijn gered. Ze zwemmen nog steeds verloren door de oceaan. 🥺',
      warningLeave: 'Wacht! Er zwemmen nog vriendjes verloren in de oceaan! Ze wachten op hulp. Weet je zeker dat je ze achterlaat?',
    },
  },
  CASTLE: {
    id: 'castle',
    name: '🏰 Kasteel',
    emoji: '🏰',
    colors: {
      primary: 'bg-stone-600',
      secondary: 'bg-amber-700',
      wall: 'bg-stone-800',
      path: 'bg-stone-700',
      player: '🤴',
      challenge: '🐉',
    },
    pathChar: '◆',
    friendlies: ['🦉', '🐈', '🐭', '🦔', '🐇', '🦊', '🦄', '🐲', '🦅', '🦢'],
    story: {
      intro: 'Alarm in het kasteel! Een ondeugende tovenaar heeft een spreuk uitgesproken en al je vriendjes zijn verstopt in de geheime gangen van het kasteel! Ze kunnen de uitgang niet meer vinden. Doorzoek alle torens en gangen om je vriendjes te bevrijden!',
      friendTexts: [
        'Hoera, de spreuk is verbroken! Ik zat vast in deze toren!',
        'Eindelijk! Het was zo donker en eng in deze gang!',
        'Dankjewel! Ik hoorde steeds vreemde geluiden!',
        'Joepie! De tovenaar had me goed verstopt!',
        'Yes! Nu kan ik weer spelen in de troonzaal!',
        'Gelukkig! Ik miste de andere kasteelbewoners!',
        'Super! Samen verslaan we de tovenaar!',
        'Fijn! Ik was bang voor de spoken in het kasteel!',
        'Geweldig! Laten we de anderen ook bevrijden!',
        'Wauw, je hebt me gevonden in dit doolhof van gangen!',
      ],
      endingComplete: 'KASTEEL BEVRIJD! 🏰 Alle vriendjes zijn weer veilig en de tovenaar is verslagen! Het kasteel is weer vrolijk en iedereen viert feest in de grote zaal. Jij bent een echte ridder!',
      endingIncomplete: 'Je verlaat het kasteel... maar sommige vriendjes zitten nog steeds gevangen in de geheime gangen. De tovenaar grinnikt... 🥺',
      warningLeave: 'Wacht! Er zitten nog vriendjes gevangen in het kasteel! De tovenaar houdt ze verborgen. Weet je zeker dat je ze achterlaat?',
    },
  },
  DINO: {
    id: 'dino',
    name: '🦕 Dinosaurus',
    emoji: '🦕',
    colors: {
      primary: 'bg-lime-700',
      secondary: 'bg-orange-600',
      wall: 'bg-lime-900',
      path: 'bg-lime-800',
      player: '🧑‍🔬',
      challenge: '🌋',
    },
    pathChar: '❋',
    friendlies: ['🦎', '🐢', '🐊', '🦤', '🐣', '🦗', '🦕', '🦖', '🦴', '🐉'],
    story: {
      intro: 'Tijdreis naar de oertijd! Je tijdmachine is geland in het dinotijdperk, maar je vriendjes zijn verspreid over het hele prehistorische landschap! De vulkaan rommelt en je moet snel zijn. Vind al je vriendjes voordat de vulkaan uitbarst!',
      friendTexts: [
        'Hoera! Ik verstopte me voor een enorme T-Rex!',
        'Eindelijk! De vulkaan maakte me zo bang!',
        'Dankjewel! Ik kon de tijdmachine niet meer vinden!',
        'Joepie! De dino\'s zijn groot, maar jij bent dapper!',
        'Yes! Nu kunnen we samen terug naar de toekomst!',
        'Gelukkig! Ik miste onze eigen tijd!',
        'Super! Deze oertijd is spannend maar ook eng!',
        'Fijn! Ik hoorde steeds een brullende dinosaurus!',
        'Geweldig! Laten we de anderen ook snel vinden!',
        'Wauw, je hebt me gevonden tussen al die fossielen!',
      ],
      endingComplete: 'TIJDREIS VOLTOOID! 🦕 Alle vriendjes zijn gevonden en veilig terug in de tijdmachine! Net op tijd, want de vulkaan barst uit! Jullie reizen veilig terug naar huis. Jij bent een echte tijdreiziger!',
      endingIncomplete: 'De tijdmachine vertrekt... maar niet iedereen is aan boord. Sommige vriendjes blijven achter in de oertijd met de dinosaurussen. 🥺',
      warningLeave: 'Wacht! Er zijn nog vriendjes in het dinoland! De vulkaan kan elk moment uitbarsten! Weet je zeker dat je ze achterlaat?',
    },
  },
  CANDY: {
    id: 'candy',
    name: '🍭 Snoep',
    emoji: '🍭',
    colors: {
      primary: 'bg-pink-500',
      secondary: 'bg-yellow-400',
      wall: 'bg-pink-700',
      path: 'bg-pink-600',
      player: '👧',
      challenge: '🪅',
    },
    pathChar: '✧',
    friendlies: ['🍩', '🧁', '🍪', '🧇', '🎀', '🍬', '🍭', '🍫', '🍰', '🍡'],
    story: {
      intro: 'Paniek in Snoepland! De Snoepkoningin is haar feest aan het voorbereiden, maar al haar zoete vriendjes zijn verdwaald in het reusachtige snoeppaleis! Ze zitten verstopt tussen de lolly\'s, karamels en chocolade. Help de Snoepkoningin om al haar vriendjes te vinden voor het feest begint!',
      friendTexts: [
        'Hoera! Ik zat vast in de karamel, zo plakkerig!',
        'Eindelijk! Ik verdwaalde tussen de reuzenlolly\'s!',
        'Dankjewel! De chocoladerivier was zo verleidelijk!',
        'Joepie! Nu kan ik mee naar het snoepfeest!',
        'Yes! Ik at bijna alle marshmallows op!',
        'Gelukkig! De zure matten waren te zuur voor mij!',
        'Super! Samen eten we de lekkerste traktaties!',
        'Fijn! Ik was bang dat ik het feest zou missen!',
        'Geweldig! Laten we de anderen ook gaan zoeken!',
        'Wauw, je hebt me gevonden in deze zoete wereld!',
      ],
      endingComplete: 'SNOEPFEEST! 🍭 Alle zoete vriendjes zijn gevonden en het feest kan beginnen! De Snoepkoningin is dolgelukkig en iedereen smult van de heerlijkste lekkernijen. Jij bent de zoetste held ooit!',
      endingIncomplete: 'Je verlaat Snoepland... maar niet alle vriendjes zijn op het feest. Ze dwalen nog rond tussen de snoepjes, alleen en verdwaald. 🥺',
      warningLeave: 'Wacht! Er zijn nog vriendjes verdwaald in Snoepland! Het feest is niet compleet zonder hen. Weet je zeker dat je ze achterlaat?',
    },
  },
  SPORTS: {
    id: 'sports',
    name: '⚽ Sport',
    emoji: '⚽',
    colors: {
      primary: 'bg-emerald-600',
      secondary: 'bg-emerald-500',
      wall: 'bg-emerald-800',
      path: 'bg-emerald-700',
      player: '🏃',
      challenge: '🏆',
    },
    pathChar: '◦',
    friendlies: ['⚽', '🏀', '🎾', '🏈', '⚾', '🏐', '🏓', '🏸', '⛳', '🎳'],
    story: {
      intro: 'Code rood in het stadion! De grote sportdag is bijna begonnen, maar je teamgenoten zijn verdwaald in het enorme sportcomplex! Ze zitten verspreid over de velden, zalen en banen. Vind al je teamgenoten zodat jullie samen de wedstrijd kunnen winnen!',
      friendTexts: [
        'Yes, gevonden! Ik was aan het opwarmen maar raakte verdwaald!',
        'Eindelijk! Het stadion is zo groot, ik vond de weg niet meer!',
        'Dankjewel! Ik hoorde het publiek maar zag niemand!',
        'Hoera! Nu kunnen we samen de wedstrijd winnen!',
        'Super! Ik oefende mijn trucjes maar verloor de groep!',
        'Gelukkig! De coach zocht me overal!',
        'Top! Samen zijn we een onverslaanbaar team!',
        'Fijn! Ik was bang dat de wedstrijd zonder mij zou beginnen!',
        'Geweldig! Laten we de rest van het team vinden!',
        'Wauw, je hebt me gevonden in dit grote sportcomplex!',
      ],
      endingComplete: 'KAMPIOEN! ⚽ Het hele team is weer bij elkaar en jullie winnen de wedstrijd! Het publiek juicht, confetti valt uit de lucht en jullie tillen de beker omhoog. Jij bent de echte MVP!',
      endingIncomplete: 'Je verlaat het stadion... maar het team is niet compleet. Zonder alle spelers kunnen jullie niet winnen. De wedstrijd gaat door zonder hen. 🥺',
      warningLeave: 'Wacht! Er zijn nog teamgenoten in het stadion! Zonder hen is het team niet compleet. Weet je zeker dat je ze achterlaat?',
    },
  },
  FOOD: {
    id: 'food',
    name: '🍕 Eten',
    emoji: '🍕',
    colors: {
      primary: 'bg-orange-500',
      secondary: 'bg-red-400',
      wall: 'bg-orange-800',
      path: 'bg-orange-600',
      player: '👨‍🍳',
      challenge: '🍳',
    },
    pathChar: '·',
    friendlies: ['🍅', '🍲', '🥕', '🍟', '🍔', '🥪', '🥞', '🍝', '🍉', '🍳'],
    story: {
      intro: 'Chaos in de keuken! Het grote kookfeest begint bijna, maar alle ingrediënten en keukenhulpjes zijn door de keuken verspreid geraakt! Ze zitten verstopt in de kasten, achter de pannen en in de koelkast. Verzamel alle vriendjes zodat het feestmaal klaargemaakt kan worden!',
      friendTexts: [
        'Hoera! Ik zat verstopt achter de grote pannen!',
        'Eindelijk! De keuken is zo\'n doolhof van kasten!',
        'Dankjewel! Het was koud in de koelkast!',
        'Joepie! Nu kan ik helpen met het kookfeest!',
        'Yes! De chef-kok heeft me nodig!',
        'Gelukkig! Ik rook al het lekkere eten maar kon er niet bij!',
        'Super! Samen maken we het lekkerste gerecht!',
        'Fijn! Ik was bang dat ik zou aanbranden!',
        'Geweldig! Laten we de andere ingrediënten ook vinden!',
        'Wauw, je hebt me gevonden in deze grote keuken!',
      ],
      endingComplete: 'SMAKELIJK! 🍕 Alle ingrediënten en hulpjes zijn gevonden! Het kookfeest is een groot succes en iedereen geniet van het heerlijke eten. Jij bent de beste chef-kok!',
      endingIncomplete: 'Je verlaat de keuken... maar niet alle ingrediënten zijn verzameld. Het feestmaal is onvolledig en niet iedereen kan mee-eten. 🥺',
      warningLeave: 'Wacht! Er zijn nog hulpjes verstopt in de keuken! Het kookfeest kan niet zonder hen. Weet je zeker dat je ze achterlaat?',
    },
  },
  TRAFFIC: {
    id: 'traffic',
    name: '🚲 Verkeer',
    emoji: '🚲',
    colors: {
      primary: 'bg-slate-600',
      secondary: 'bg-slate-500',
      wall: 'bg-slate-800',
      path: 'bg-slate-700',
      player: '🚶',
      challenge: '🚦',
    },
    pathChar: '═',
    friendlies: ['🚗', '🚌', '🚲', '🚁', '🛵', '🛬', '🚤', '🚂', '🚄', '🛴'],
    story: {
      intro: 'Verkeerschaos! Een grote file heeft alle voertuigen door de hele stad verspreid! Je voertuigvriendjes staan vast op kruispunten, in tunnels en op rotondes. Navigeer door het verkeer en breng alle voertuigen veilig naar de grote garage!',
      friendTexts: [
        'Toet toet! Ik stond al uren vast bij het stoplicht!',
        'Eindelijk! Deze rotonde maakte me duizelig!',
        'Dankjewel! De tunnel was zo donker en eng!',
        'Hoera! Nu kan ik weer scheuren over de weg!',
        'Yes! Het verkeer was zo druk, ik kon nergens heen!',
        'Gelukkig! Mijn motor begon al te sputteren!',
        'Super! Samen rijden we naar de finish!',
        'Fijn! Ik miste mijn plek in de garage!',
        'Geweldig! Laten we de anderen uit de file halen!',
        'Wauw, je hebt me gevonden in al dit verkeer!',
      ],
      endingComplete: 'GROEN LICHT! 🚲 Alle voertuigen zijn veilig in de garage! De wegen zijn weer vrij en iedereen toetert van blijdschap. Jij bent de beste verkeersagent!',
      endingIncomplete: 'Je verlaat de stad... maar sommige voertuigen staan nog steeds vast in het verkeer. Ze wachten nog steeds op hulp. 🥺',
      warningLeave: 'Wacht! Er staan nog voertuigen vast in het verkeer! Ze kunnen nergens heen zonder jouw hulp. Weet je zeker dat je ze achterlaat?',
    },
  },
  FARM: {
    id: 'farm',
    name: '🚜 Boerderij',
    emoji: '🚜',
    colors: {
      primary: 'bg-amber-600',
      secondary: 'bg-amber-500',
      wall: 'bg-amber-900',
      path: 'bg-amber-700',
      player: '👨‍🌾',
      challenge: '🌾',
    },
    pathChar: '≋',
    friendlies: ['🐄', '🐷', '🐔', '🐑', '🐴', '🦆', '🐐', '🦃', '🐕', '🐈'],
    story: {
      intro: 'Het hek staat open! Alle boerderijdieren zijn ontsnapt en dwalen nu rond over de velden, in de schuren en tussen het hooi! De boer heeft dringend hulp nodig om alle dieren terug te vinden voordat het donker wordt!',
      friendTexts: [
        'Boe! Moe! Ik verdwaalde tussen het hoge koren!',
        'Eindelijk! De wei was zo groot, ik vond de stal niet meer!',
        'Dankjewel! Ik verstopte me in het hooi maar kon er niet meer uit!',
        'Tok tok! Nu kan ik weer lekker scharrelen op het erf!',
        'Yes! De boer zocht me overal!',
        'Gelukkig! Ik miste mijn warme stal!',
        'Super! Samen gaan we terug naar de boerderij!',
        'Fijn! Het was eenzaam zo alleen in het veld!',
        'Geweldig! Laten we de andere dieren ook vinden!',
        'Wauw, je hebt me gevonden op deze grote boerderij!',
      ],
      endingComplete: 'BOERDERIJ COMPLEET! 🚜 Alle dieren zijn weer veilig in de stal en op het erf! De boer is dolgelukkig en iedereen krijgt extra voer als beloning. Jij bent de beste boerenhelper!',
      endingIncomplete: 'Je verlaat de boerderij... maar niet alle dieren zijn terug. Ze dwalen nog steeds rond, ver van hun warme stal. 🥺',
      warningLeave: 'Wacht! Er zijn nog dieren verdwaald op de boerderij! De boer maakt zich zorgen. Weet je zeker dat je ze achterlaat?',
    },
  },
  MUSIC: {
    id: 'music',
    name: '🎵 Muziek',
    emoji: '🎵',
    colors: {
      primary: 'bg-violet-600',
      secondary: 'bg-fuchsia-500',
      wall: 'bg-violet-900',
      path: 'bg-violet-700',
      player: '🎤',
      challenge: '🎼',
    },
    pathChar: '♪',
    friendlies: ['🎸', '🥁', '🎹', '🎺', '🎻', '🎷', '🎤', '🪗', '🪕', '🪈'],
    story: {
      intro: 'Stilte in de concertzaal! Het grote concert begint zo, maar alle instrumenten zijn zoekgeraakt in het muziekgebouw! Ze liggen verspreid in kleedkamers, oefenruimtes en backstage. Vind alle instrumenten zodat het orkest kan spelen!',
      friendTexts: [
        'La la la! Ik was mijn toonladders aan het oefenen!',
        'Eindelijk! De concertzaal is zo groot, ik raakte verdwaald!',
        'Dankjewel! Mijn snaren moeten nog gestemd worden!',
        'Hoera! Nu kan ik meedoen met het concert!',
        'Yes! De dirigent zocht me overal!',
        'Gelukkig! Ik miste mijn plekje in het orkest!',
        'Super! Samen maken we de mooiste muziek!',
        'Fijn! Het was zo stil zonder de andere instrumenten!',
        'Geweldig! Laten we de rest van het orkest vinden!',
        'Wauw, je hebt me gevonden in dit muziekpaleis!',
      ],
      endingComplete: 'APPLAUS! 🎵 Alle instrumenten zijn gevonden en het concert is een daverend succes! Het publiek klapt, juicht en vraagt om een toegift. Jij bent een echte muziekheld!',
      endingIncomplete: 'Het concert begint... maar niet alle instrumenten zijn er. De muziek klinkt onvolledig en het publiek is teleurgesteld. 🥺',
      warningLeave: 'Wacht! Er zijn nog instrumenten zoek in het muziekgebouw! Het concert kan niet zonder hen. Weet je zeker dat je ze achterlaat?',
    },
  },
  PIRATES: {
    id: 'pirates',
    name: '🏴‍☠️ Piraten',
    emoji: '🏴‍☠️',
    colors: {
      primary: 'bg-yellow-700',
      secondary: 'bg-yellow-600',
      wall: 'bg-yellow-900',
      path: 'bg-yellow-800',
      player: '🏴‍☠️',
      challenge: '🗺️',
    },
    pathChar: '⚓',
    friendlies: ['🦜', '🐙', '🦈', '🐚', '🦞', '🦑', '🪼', '⚓', '💰', '🏝️'],
    story: {
      intro: 'Ahoy, matroos! Een hevige storm heeft je piratenbemanning overboord geslagen! Ze zijn verspreid over het mysterieuze pirateneiland en wachten om gered te worden. Doorzoek alle grotten, stranden en de jungle om je crew weer te verzamelen!',
      friendTexts: [
        'Arrr! Eindelijk! Ik spoelde aan op dit verlaten strand!',
        'Ahoy! De golven namen me mee naar deze grot!',
        'Yo ho ho! Ik vond een schatkist, maar ik zat alleen!',
        'Dankjewel kapitein! De storm was verschrikkelijk!',
        'Yes! Nu kunnen we weer op schattenjacht!',
        'Gelukkig! Ik miste ons piratenschip!',
        'Arrr! Samen zijn we de sterkste piraten van de zee!',
        'Fijn! Ik was bang voor het zeemonster!',
        'Geweldig! Laten we de rest van de crew redden!',
        'Wauw, je hebt me gevonden op dit wilde eiland!',
      ],
      endingComplete: 'SCHAT GEVONDEN! 🏴‍☠️ De hele bemanning is weer aan boord en jullie hebben de grootste schat van het eiland gevonden! Het schip zeilt naar de horizon voor nieuwe avonturen. Jij bent de dapperste kapitein!',
      endingIncomplete: 'Het schip vertrekt... maar niet alle bemanningsleden zijn aan boord. Ze blijven alleen achter op het eiland. 🥺',
      warningLeave: 'Arrr! Er zijn nog matrozen op het eiland! Een echte kapitein laat zijn crew niet achter. Weet je zeker dat je ze achterlaat?',
    },
  },
};

export const getTheme = (themeId) => {
  return Object.values(THEMES).find((t) => t.id === themeId) || THEMES.SPACE;
};
