// Thema's die kids van groep 4 leuk vinden
export const THEMES = {
  SPACE: {
    id: 'space',
    name: '🚀 Ruimte',
    emoji: '🚀',
    colors: {
      primary: 'bg-indigo-900',
      secondary: 'bg-purple-800',
      wall: 'bg-gray-800',
      path: 'bg-indigo-950',
      player: '👨‍🚀',
      challenge: '👽',
    },
    pathChar: '✦',
    friendlies: ['🛸', '🌟', '🦄', '🧸', '🐶', '🌌'],
  },
  JUNGLE: {
    id: 'jungle',
    name: '🦁 Jungle',
    emoji: '🦁',
    colors: {
      primary: 'bg-green-700',
      secondary: 'bg-green-600',
      wall: 'bg-green-900',
      path: 'bg-green-800',
      player: '🧒',
      challenge: '🐒',
    },
    pathChar: '✿',
    friendlies: ['🦜', '🐘', '🦋', '🐸', '🐰', '🦁'],
  },
  OCEAN: {
    id: 'ocean',
    name: '🌊 Oceaan',
    emoji: '🌊',
    colors: {
      primary: 'bg-blue-600',
      secondary: 'bg-cyan-500',
      wall: 'bg-blue-900',
      path: 'bg-blue-700',
      player: '🤿',
      challenge: '🐠',
    },
    pathChar: '~',
    friendlies: ['🐙', '🦀', '🐬', '🦭', '🐚', '🦈'],
  },
  CASTLE: {
    id: 'castle',
    name: '🏰 Kasteel',
    emoji: '🏰',
    colors: {
      primary: 'bg-stone-600',
      secondary: 'bg-amber-700',
      wall: 'bg-stone-800',
      path: 'bg-stone-700',
      player: '🤴',
      challenge: '🐉',
    },
    pathChar: '◆',
    friendlies: ['🦉', '🐈', '🐭', '🦔', '🐇', '🦊'],
  },
  DINO: {
    id: 'dino',
    name: '🦕 Dinosaurus',
    emoji: '🦕',
    colors: {
      primary: 'bg-lime-700',
      secondary: 'bg-orange-600',
      wall: 'bg-lime-900',
      path: 'bg-lime-800',
      player: '🧑‍🔬',
      challenge: '🦖',
    },
    pathChar: '❋',
    friendlies: ['🦎', '🐢', '🐊', '🦤', '🐣', '🦗'],
  },
  CANDY: {
    id: 'candy',
    name: '🍭 Snoepland',
    emoji: '🍭',
    colors: {
      primary: 'bg-pink-500',
      secondary: 'bg-yellow-400',
      wall: 'bg-pink-700',
      path: 'bg-pink-600',
      player: '👧',
      challenge: '🍬',
    },
    pathChar: '✧',
    friendlies: ['🍩', '🧁', '🍪', '🧇', '🎀', '�'],
  },
  SPORTS: {
    id: 'sports',
    name: '⚽ Sport',
    emoji: '⚽',
    colors: {
      primary: 'bg-emerald-600',
      secondary: 'bg-emerald-500',
      wall: 'bg-emerald-800',
      path: 'bg-emerald-700',
      player: '🏃',
      challenge: '🏆',
    },
    pathChar: '◦',
    friendlies: ['⚽', '🏀', '🎾', '🏈', '⚾', '�'],
  },
  FOOD: {
    id: 'food',
    name: '🍕 Eten',
    emoji: '🍕',
    colors: {
      primary: 'bg-orange-500',
      secondary: 'bg-red-400',
      wall: 'bg-orange-800',
      path: 'bg-orange-600',
      player: '👨‍🍳',
      challenge: '🍳',
    },
    pathChar: '·',
    friendlies: ['🍕', '🍔', '🌮', '🍟', '🍦', '🥪'],
  },
  TRAFFIC: {
    id: 'traffic',
    name: '🚗 Verkeer',
    emoji: '🚗',
    colors: {
      primary: 'bg-slate-600',
      secondary: 'bg-slate-500',
      wall: 'bg-slate-800',
      path: 'bg-slate-700',
      player: '🚶',
      challenge: '🚦',
    },
    pathChar: '═',
    friendlies: ['🚗', '🚌', '🚲', '🚁', '🛵', '�'],
  },
  FARM: {
    id: 'farm',
    name: '🚜 Boerderij',
    emoji: '🚜',
    colors: {
      primary: 'bg-amber-600',
      secondary: 'bg-amber-500',
      wall: 'bg-amber-900',
      path: 'bg-amber-700',
      player: '👨‍🌾',
      challenge: '🌾',
    },
    pathChar: '≋',
    friendlies: ['🐄', '🐷', '🐔', '🐑', '🐴', '🦆'],
  },
  MUSIC: {
    id: 'music',
    name: '🎵 Muziek',
    emoji: '🎵',
    colors: {
      primary: 'bg-violet-600',
      secondary: 'bg-fuchsia-500',
      wall: 'bg-violet-900',
      path: 'bg-violet-700',
      player: '🎤',
      challenge: '🎼',
    },
    pathChar: '♪',
    friendlies: ['🎸', '🥁', '🎹', '🎺', '🎻', '🎷'],
  },
  PIRATES: {
    id: 'pirates',
    name: '🏴‍☠️ Piraten',
    emoji: '🏴‍☠️',
    colors: {
      primary: 'bg-yellow-700',
      secondary: 'bg-yellow-600',
      wall: 'bg-yellow-900',
      path: 'bg-yellow-800',
      player: '🏴‍☠️',
      challenge: '💎',
    },
    pathChar: '⚓',
    friendlies: ['🦜', '🐙', '🦈', '🐚', '🦞', '🦑'],
  },
};

export const getTheme = (themeId) => {
  return Object.values(THEMES).find((t) => t.id === themeId) || THEMES.SPACE;
};
