// Thema's die kids van groep 4 leuk vinden
export const THEMES = {
  SPACE: {
    id: 'space',
    name: '🚀 Ruimte',
    emoji: '🚀',
    colors: {
      primary: 'bg-indigo-900',
      secondary: 'bg-purple-800',
      wall: 'bg-gray-800',
      path: 'bg-indigo-950',
      player: '👨‍🚀',
      challenge: '👽',
    },
    pathChar: '✦',
    friendlies: ['🛸', '🌟', '🌍', '🚀', '☄️', '🌌', '👾', '🛰️', '🪐', '🌠'],
    friendTexts: [
      'Bedankt dat je me hebt gevonden tussen de sterren!',
      'Ik was verdwaald in het heelal, super dat je me helpt!',
      'Wow, samen vliegen we naar de maan!',
      'Jij bent mijn held in de ruimte!',
      'Zonder jou was ik voor altijd kwijt in het heelal!',
      'Je hebt me gered van een zwart gat!',
      'Nu kan ik weer op avontuur in mijn UFO!',
      'Dankzij jou zie ik alle planeten weer!',
      'Samen zijn we sneller dan het licht!',
      'Je bent de beste astronautenvriend ooit!',
    ],
  },
  JUNGLE: {
    id: 'jungle',
    name: '🦁 Jungle',
    emoji: '🦁',
    colors: {
      primary: 'bg-green-700',
      secondary: 'bg-green-600',
      wall: 'bg-green-900',
      path: 'bg-green-800',
      player: '🧒',
      challenge: '🐒',
    },
    pathChar: '✿',
    friendlies: ['🦜', '🐘', '🦋', '🐸', '🐰', '🦁', '🦅', '🦧', '🦓', '🦥'],
    friendTexts: [
      'Bedankt dat je me uit de jungle hebt gehaald!',
      'Met jou voel ik me veilig tussen de bomen!',
      'Samen slingeren we als apen!',
      'Jij bent mijn held in het oerwoud!',
      'Nu kan ik weer springen in de modder!',
      'Dankzij jou kan ik weer brullen als een leeuw!',
      'We gaan samen bananen zoeken!',
      'Ik was verdwaald tussen de tijgers, bedankt!',
      'Met jou is de jungle een feestje!',
      'Je bent mijn beste junglemaatje!',
    ],
  },
  OCEAN: {
    id: 'ocean',
    name: '🌊 Oceaan',
    emoji: '🌊',
    colors: {
      primary: 'bg-blue-600',
      secondary: 'bg-cyan-500',
      wall: 'bg-blue-900',
      path: 'bg-blue-700',
      player: '🤿',
      challenge: '🐠',
    },
    pathChar: '~',
    friendlies: ['🐙', '🦀', '🐬', '🦭', '🐚', '🦈', '🐳', '🦑', '🐡', '🪸'],
    friendTexts: [
      'Bedankt dat je me uit de diepe zee hebt gehaald!',
      'Nu kan ik weer zwemmen met mijn vrienden!',
      'Samen maken we bubbels onder water!',
      'Jij bent mijn held van de oceaan!',
      'Dankzij jou ben ik niet meer verdwaald tussen het koraal!',
      'We gaan samen schatten zoeken op de zeebodem!',
      'Met jou voel ik me als een vis in het water!',
      'Je hebt me gered van de haai!',
      'Nu kan ik weer zingen met de walvissen!',
      'Je bent de beste duikvriend ooit!',
    ],
  },
  CASTLE: {
    id: 'castle',
    name: '🏰 Kasteel',
    emoji: '🏰',
    colors: {
      primary: 'bg-stone-600',
      secondary: 'bg-amber-700',
      wall: 'bg-stone-800',
      path: 'bg-stone-700',
      player: '🤴',
      challenge: '🐉',
    },
    pathChar: '◆',
    friendlies: ['🦉', '🐈', '🐭', '🦔', '🐇', '🦊', '🦄', '🐲', '🦅', '🦢'],
    friendTexts: [
      'Bedankt dat je me uit de toren hebt gehaald!',
      'Nu kan ik weer spelen in het kasteel!',
      'Samen verslaan we de draak!',
      'Jij bent mijn ridder in glanzend harnas!',
      'Dankzij jou kan ik weer feesten op het bal!',
      'We gaan samen op zoek naar de schat!',
      'Met jou voel ik me veilig in het kasteel!',
      'Je hebt me gered van de boze tovenaar!',
      'Nu kan ik weer vliegen met de uil!',
      'Je bent de beste kasteelvriend ooit!',
    ],
  },
  DINO: {
    id: 'dino',
    name: '🦕 Dinosaurus',
    emoji: '🦕',
    colors: {
      primary: 'bg-lime-700',
      secondary: 'bg-orange-600',
      wall: 'bg-lime-900',
      path: 'bg-lime-800',
      player: '🧑‍🔬',
      challenge: '🌋',
    },
    pathChar: '❋',
    friendlies: ['🦎', '🐢', '🐊', '🦤', '🐣', '🦗', '🦕', '🦖', '🦴', '🐉'],
    friendTexts: [
      'Bedankt dat je me uit het dinobos hebt gehaald!',
      'Nu kan ik weer rennen met de dino’s!',
      'Samen brullen we als echte dino’s!',
      'Jij bent mijn held van de oertijd!',
      'Dankzij jou ben ik niet meer bang voor de vulkaan!',
      'We gaan samen op zoek naar fossielen!',
      'Met jou voel ik me superstoer!',
      'Je hebt me gered van de T-Rex!',
      'Nu kan ik weer spelen met de dino-eieren!',
      'Je bent de beste dinovriend ooit!',
    ],
  },
  CANDY: {
    id: 'candy',
    name: '🍭 Snoep',
    emoji: '🍭',
    colors: {
      primary: 'bg-pink-500',
      secondary: 'bg-yellow-400',
      wall: 'bg-pink-700',
      path: 'bg-pink-600',
      player: '👧',
      challenge: '🪅',
    },
    pathChar: '✧',
    friendlies: ['🍩', '🧁', '🍪', '🧇', '🎀', '🍬', '🍭', '🍫', '🍰', '🍡'],
    friendTexts: [
      'Bedankt dat je me hebt gevonden, ik bleef maar snoepen!',
      'Nu kan ik weer smullen van al het lekkers!',
      'Samen maken we de grootste suikerspin!',
      'Jij bent mijn held in snoepland!',
      'Dankzij jou ben ik niet meer plakkerig!',
      `We gaan samen lolly's zoeken!`,
      'Met jou is elke dag een feestje!',
      'Je hebt me gered van de zure matten!',
      'Nu kan ik weer dansen tussen de snoepjes!',
      'Je bent de zoetste vriend ooit!',
    ],
  },
  SPORTS: {
    id: 'sports',
    name: '⚽ Sport',
    emoji: '⚽',
    colors: {
      primary: 'bg-emerald-600',
      secondary: 'bg-emerald-500',
      wall: 'bg-emerald-800',
      path: 'bg-emerald-700',
      player: '🏃',
      challenge: '🏆',
    },
    pathChar: '◦',
    friendlies: ['⚽', '🏀', '🎾', '🏈', '⚾', '🏐', '🏓', '🏸', '⛳', '🎳'],
    friendTexts: [
      'De wedstrijd is al voorbij, mag ik met jou mee het stadion uit?',
      'Nu kan ik weer scoren met mijn team!',
      'Samen winnen we de beker!',
      'Jij bent mijn sportheld!',
      'Dankzij jou ben ik niet meer geblesseerd!',
      'We gaan samen trainen voor de finale!',
      'Met jou is elke wedstrijd leuk!',
      'Je hebt me gered van de strafschop!',
      'Nu kan ik weer juichen op het veld!',
      'Je bent de beste sportmaat ooit!',
    ],
  },
  FOOD: {
    id: 'food',
    name: '🍕 Eten',
    emoji: '🍕',
    colors: {
      primary: 'bg-orange-500',
      secondary: 'bg-red-400',
      wall: 'bg-orange-800',
      path: 'bg-orange-600',
      player: '👨‍🍳',
      challenge: '🍳',
    },
    pathChar: '·',
    friendlies: ['🍅', '🍲', '🥕', '🍟', '🍔', '🥪', '🥞', '🍝', '🍉', '🍳'],
    friendTexts: [
      'Bedankt dat je me uit de keuken hebt gehaald!',
      'Nu kan ik weer smullen van al het eten!',
      'Samen bakken we de lekkerste pannenkoeken!',
      'Jij bent mijn chef-kok!',
      'Dankzij jou ben ik niet meer hongerig!',
      'We gaan samen pizza’s maken!',
      'Met jou is elke maaltijd een feest!',
      'Je hebt me gered van de hete oven!',
      'Nu kan ik weer proeven van alles!',
      'Je bent de smakelijkste vriend ooit!',
    ],
  },
  TRAFFIC: {
    id: 'traffic',
    name: '🚲 Verkeer',
    emoji: '🚲',
    colors: {
      primary: 'bg-slate-600',
      secondary: 'bg-slate-500',
      wall: 'bg-slate-800',
      path: 'bg-slate-700',
      player: '🚶',
      challenge: '🚦',
    },
    pathChar: '═',
    friendlies: ['🚗', '🚌', '🚲', '🚁', '🛵', '🛬', '🚤', '🚂', '🚄', '🛴'],
    friendTexts: [
      'Bedankt dat je me uit de file hebt gehaald!',
      'Nu kan ik weer racen over de weg!',
      'Samen toeteren we door de stad!',
      'Jij bent mijn verkeersheld!',
      'Dankzij jou ben ik niet meer verdwaald!',
      'We gaan samen op reis!',
      'Met jou is elke rit leuk!',
      'Je hebt me gered van de stoplichten!',
      'Nu kan ik weer scheuren met mijn auto!',
      'Je bent de snelste vriend ooit!',
    ],
  },
  FARM: {
    id: 'farm',
    name: '🚜 Boerderij',
    emoji: '🚜',
    colors: {
      primary: 'bg-amber-600',
      secondary: 'bg-amber-500',
      wall: 'bg-amber-900',
      path: 'bg-amber-700',
      player: '👨‍🌾',
      challenge: '🌾',
    },
    pathChar: '≋',
    friendlies: ['🐄', '🐷', '🐔', '🐑', '🐴', '🦆', '🐐', '🦃', '🐕', '🐈'],
    friendTexts: [
      'Bedankt dat je me uit de stal hebt gehaald!',
      'Nu kan ik weer spelen op de boerderij!',
      'Samen voeren we de dieren!',
      'Jij bent mijn boerderijheld!',
      'Dankzij jou ben ik niet meer verdwaald in het hooi!',
      'We gaan samen eieren rapen!',
      'Met jou is elke dag een dierendag!',
      'Je hebt me gered van de modderpoel!',
      'Nu kan ik weer rennen over het erf!',
      'Je bent de beste boerderijvriend ooit!',
    ],
  },
  MUSIC: {
    id: 'music',
    name: '🎵 Muziek',
    emoji: '🎵',
    colors: {
      primary: 'bg-violet-600',
      secondary: 'bg-fuchsia-500',
      wall: 'bg-violet-900',
      path: 'bg-violet-700',
      player: '🎤',
      challenge: '🎼',
    },
    pathChar: '♪',
    friendlies: ['🎸', '🥁', '🎹', '🎺', '🎻', '🎷', '🎤', '🪗', '🪕', '🪈'],
    friendTexts: [
      'Bedankt dat je me uit de muziekzaal hebt gehaald!',
      'Nu kan ik weer zingen en dansen!',
      'Samen maken we de mooiste muziek!',
      'Jij bent mijn muziekheld!',
      'Dankzij jou ben ik niet meer uit de maat!',
      'We gaan samen een concert geven!',
      'Met jou klinkt alles vrolijk!',
      'Je hebt me gered van de valse noten!',
      'Nu kan ik weer spelen op mijn instrument!',
      'Je bent de beste muziekmaat ooit!',
    ],
  },
  PIRATES: {
    id: 'pirates',
    name: '🏴‍☠️ Piraten',
    emoji: '🏴‍☠️',
    colors: {
      primary: 'bg-yellow-700',
      secondary: 'bg-yellow-600',
      wall: 'bg-yellow-900',
      path: 'bg-yellow-800',
      player: '🏴‍☠️',
      challenge: '🗺️',
    },
    pathChar: '⚓',
    friendlies: ['🦜', '🐙', '🦈', '🐚', '🦞', '🦑', '🪼', '⚓', '💰', '🏝️'],
    friendTexts: [
      'Bedankt dat je me uit het piratenschip hebt gehaald!',
      'Nu kan ik weer schatten zoeken!',
      'Samen varen we over de zee!',
      'Jij bent mijn piratenheld!',
      'Dankzij jou ben ik niet meer overboord!',
      'We gaan samen op avontuur!',
      'Met jou is elke dag een schattenjacht!',
      'Je hebt me gered van de haai!',
      'Nu kan ik weer zingen met de papegaai!',
      'Je bent de stoerste piraat ooit!',
    ],
  },
};

export const getTheme = (themeId) => {
  return Object.values(THEMES).find((t) => t.id === themeId) || THEMES.SPACE;
};
